import { Injectable } from '@angular/core';
import { FaceSnap } from './../models/face-snap.model';

@Injectable({
	providedIn: 'root'
})

export class FaceSnapsService {

	faceSnaps: FaceSnap[] = [
			{
				id: 1,
				title: 'cyberpunk realistic chipmunk part.2',
				description: 'This image has been generated by IA',
				imageUrl: 'https://images.nightcafe.studio/jobs/BBCSGfmVzXeQKrXQqqR9/BBCSGfmVzXeQKrXQqqR9.jpg',
				createdDate: new Date(),
				snaps: 32,
				location: 'cyberspace'
			},
			{
				id: 2,
				title: 'teddy bear apocalypse part.1',
				description: 'This image has been generated by IA',
				imageUrl: 'https://images.nightcafe.studio/jobs/FugV0qmAVY0hxAwGY7gt/FugV0qmAVY0hxAwGY7gt.jpg',
				createdDate: new Date(),
				snaps: 155,
			},
			{
				id: 3,
				title: `unicorn's rave party`,
				description: 'This image has been generated by IA part.3',
				imageUrl: 'https://images.nightcafe.studio/jobs/WRbiuKhVmMqK4cfZ4S6K/WRbiuKhVmMqK4cfZ4S6K.jpg',
				createdDate: new Date(),
				snaps: 250
			}
		];

	getAllFaceSnaps(): FaceSnap[] {
		return this.faceSnaps;
	}

	getFaceSnapById(faceSnapId: number): FaceSnap {
		const faceSnap = this.faceSnaps.find(faceSnap => faceSnap.id === faceSnapId);
		if (!faceSnap) {
			throw new Error('FaceSnap not found!');
		} else {
			return faceSnap;
		}
	}

	snapFaceSnapById(faceSnapId: number, snapType: 'snap' | 'unsnap'): void {
		const faceSnap = this.getFaceSnapById(faceSnapId);
		snapType === 'snap' ? faceSnap.snaps++ : faceSnap.snaps--;
	}
}